branch: main
directory:
- test-dir
download-external-modules: true
evaluate-variables: true
external-checks-dir:
- extra_checks
external-modules-download-path: .external_modules
framework: all
output: cli
